# -*- coding: utf-8 -*-
"""w5 Linda

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hdm_6nioGCuf2ngpiMpMbOEa0WI6OLN0

1. Using for loop, create nested list from dictionary, see example

```
# This is formatted as code
```
"""

fruits = {'banana':3,'apple':2, 'mango':1, 'kiwi':5}

listfruits=[]

for item in fruits:
  number_of_fruits=(fruits[item])
 
for x in range(number_of_fruits):
    
  listfruits.append(item)
    
print (listfruits)
#I'm unsure why is it only calling kiwi

"""2. Select the shortest element from the list"""

fruits = ['banana','apple', 'mango', 'kiwi']

shortest=(min(fruits, key=len))

print(shortest)

"""3. Using loops and conditions, count occurrence of numbers, letters and other symbols in the string"""

string="What a to do to die today at a 1/4 or 2 to 2. A terrible difficult thing to say but a harder thing still to do. The dragon will come at the beat of the drum with a rat-tat-tat-tat-tat-tattoo at a 1/4 or 2 to 2 today, at a 1/4 or 2 to 2."

def counting():
  number_count=0
  letter_count=0
  other_symbols=0
  for letter in string:
    if letter == (string.isalpha()):
      letter_count +=1
print (counting())



#I was unable to complete this exercise

"""4. Calculate dog's age in human years"""

dog_to_human= {1:15,2:24,3:28,4:32,5:36,6:42,7:47,8:51,9:56,10:60}

dog_age_input=int(input("How old is your dog? "))


  
conversion=(dog_to_human[dog_age_input])

print ("Your dog is {} in human years!".format(conversion))

"""5. Count the number of even and odd numbers from a series of numbers."""

seq = [1,44,30,15,2,18]
count_odd=0
count_even=0

for x in seq:
  if x % 2:
    count_odd +=1
  else:
    count_even +=1
    
print("even numbers {}".format(count_even))
print("odd numbers {}".format(count_odd))

"""6. Using loops, print following pattern"""

for i in range (0,4):
  for x in range(0,i+1):
    print ("*",end="")
  print ("\r")

"""7. Using list comprehensions, transform all vowels within the string to upper case"""

string="python"
vowels=('a','e','i','o','u','y')
for letter in string:
  if letter in (vowels):
    (letter.upper())
  else:
    pass
  
print (string)


#I'm not sure why this didn't work

"""8. Print position number of the letter"""

dictionary={'a':'1','b':'2','c':'3','d':'4','e':'5','f':'6','g':'7','h':'8',
    'i':'9','j':'10','k':'11','l':'12','m':'13','n':'14','o':'15','p':'16','q':'17',
    'r':'18','s':'19','t':'20','u':'21','v':'22','w':'23','x':'24','y':'25','z':'26'
    }

letter=(input("Please enter a letter "))

for i in (letter):
  print(dictionary[i])

"""9. Find the median of three values (do not use median function)"""

a=input("enter your first value")
b=input("enter your second value")
c=input("enter your third value")
sortedlist=(a,b,c)

sortedlist=sorted(sortedlist)
median=(sortedlist[1])
print ("Your median is {}".format(median))

"""10. Using break and continue statements, print numbers"""

fave_num=int(input("What is your favourite number?"))

while fave_num == 13:
  print ('Please select a different number')
  fave_num=int(input("What is your favourite number?"))

else:
  for number in range(int(fave_num)+1):
    if number != 13:
      print(number)

